plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.github.ursoblanco23'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.googlecode.libphonenumber:libphonenumber:9.0.37'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	/*jpa*/
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	/*postgreSQL*/
	runtimeOnly 'org.postgresql:postgresql'

    // spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // 데이터 유효성 검증
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // JWT API (필수)
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    // JWT 구현체 (런타임에 필요)
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    // JSON 파싱을 위한 jackson 확장 (런타임에 필요, Gson 사용 시 jjwt-gson 추가)
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
