spring.application.name=capoeira-in-korea-backend

server.port=8080
server.servlet.context-path=/api

# \uB85C\uAE45 \uC124\uC815

logging.level.root=INFO
logging.level.io.github.ursoblanco23.capoeira_in_korea_backend=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=DEBUG

# \uB354 \uC790\uC138\uD55C \uB85C\uAE45

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.resource.ResourceHttpRequestHandler=DEBUG
logging.level.org.springframework.security=DEBUG

# PostgreSQL \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0 \uC124\uC815

### 아래에 환경변수들은 /backend 내에 env.dev를 ide의 환경변수로 참조해와서 주입받도록 하기.
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA \uC124\uC815

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL \uB85C\uADF8 \uCD9C\uB825

logging.level.org.hibernate.SQL=DEBUG

# Spring Boot 3.x \uD30C\uB77C\uBBF8\uD130 \uBC14\uC778\uB529 \uAC12 \uCD9C\uB825

logging.level.org.hibernate.orm.jdbc.bind=TRACE

## \uCD94\uAC00\uC801\uC778 \uC0C1\uC138 \uB85C\uAE45

#logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.org.springframework.transaction=DEBUG
#logging.level.org.hibernate=INFO
#logging.level.com.zaxxer.hikari=DEBUG

# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uAE30\uC874 \uC124\uC815

file.upload.images-path=/upload/images
file.upload.videos-path=/upload/videos
file.upload.thumbnail-size=500
file.upload.allowed-image-types=image/jpeg,image/jpg,image/png,image/webp
file.upload.allowed-image-extensions=jpeg,jpg,png,webp


# Media 설정 정보
storage.local.base-path=${STORAGE_LOCAL_BASE_PATH}
file.upload.base-dir=${STORAGE_LOCAL_BASE_DIR}

# Image

file.upload.image.base-dir=${file.upload.base-dir}/images
file.upload.image.general-dir=${file.upload.image.base-dir}/general
file.upload.image.thumbnail-dir=${file.upload.image.base-dir}/thumbnails
file.upload.image.profile-dir=${file.upload.image.base-dir}/profiles
file.upload.image.max-size=2097152
file.upload.image.thumbnail-size=500
file.upload.image.allowed-types=image/jpeg,image/jpg,image/png,image/webp
file.upload.image.allowed-extensions=jpeg,jpg,png,webp

# Video

file.upload.video.base-dir=${file.upload.base-dir}/videos
file.upload.video.max-size=104857600
file.upload.video.allowed-types=video/mp4
file.upload.video.allowed-extensions=mp4

# Spring \uBA40\uD2F0\uD30C\uD2B8 \uC124\uC815

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB

# JWT

security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=capo-korea
security.jwt.access-minutes=30
